services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: mndr
      POSTGRES_PASSWORD: mndr
      POSTGRES_DB: colby
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
